"""empty message

Revision ID: 389d796b52f3
Revises: acb9231e844f
Create Date: 2022-06-08 15:52:34.145816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389d796b52f3'
down_revision = 'acb9231e844f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['id'])
    op.create_unique_constraint(None, 'Show', ['id'])
    op.create_unique_constraint(None, 'Venue', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Show', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
